---
- include_role:
    name: logger
  vars:
    log_label: restart services
    log_data:
      message: started

- name: restart services
  win_shell: >
    tsm restart
    --request-timeout 3600
    -u {{ tableau_local_admin_user }}
    -p {{ tableau_local_admin_pass }}
  args:
    chdir: "{{ tableau_bin_dir }}"
    executable: cmd
  async: 3600

- include_role:
    name: logger
  vars:
    log_label: restart services
    log_data:
      message: finished
